*** Variables ***
${JDD_CATEGORY}               TABLETS
${JDD_PRODUCT_NAME}           HP ElitePad 1000 G2
${JDD_PRODUCT_NAME_UPPER}     HP ELITEPAD 1000 G2 TABLET
${JDD_CLICS_PREMIER_AJOUT}    ${2}
${JDD_CLICS_DEUXIEME_AJOUT}   ${1}
